<a href="https://colab.research.google.com/github/arifroska/PrakAPM/blob/main/Bernoulli_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#import data
from google.colab import files
uploaded = files.upload()

Saving spam.csv to spam.csv


In [33]:
import numpy as np 
import pandas as pd 
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.naive_bayes import BernoulliNB 
from sklearn.feature_extraction.text import CountVectorizer

In [34]:
import io
df = pd.read_csv(io.BytesIO(uploaded['spam.csv']), encoding= 'latin-1')
# df = pd.read_csv('spam.csv', encoding= 'latin-1')
df.head(n=10)

class                                            message Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   
5  spam  FreeMsg Hey there darling it's been 3 week's n...        NaN   
6   ham  Even my brother is not like to speak with me. ...        NaN   
7   ham  As per your request 'Melle Melle (Oru Minnamin...        NaN   
8  spam  WINNER!! As a valued network customer you have...        NaN   
9  spam  Had your mobile 11 months or more? U R entitle...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  
5        NaN        NaN  
6        NaN        NaN  
7        NaN        NaN  
8        NaN        NaN  
9        NaN        NaN

In [35]:
df.shape

(5572, 5)

In [36]:
df= df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1)

In [37]:
df.shape

(5572, 2)

In [38]:
np.unique(df['class'])

array(['ham', 'spam'], dtype=object)

In [39]:
np.unique(df['message'])

array([' &lt;#&gt;  in mca. But not conform.',
       ' &lt;#&gt;  mins but i had to stop somewhere first.',
       ' &lt;DECIMAL&gt; m but its not a common car here so its better to buy from china or asia. Or if i find it less expensive. I.ll holla',
       ..., 'ÌÏ thk of wat to eat tonight.', 'ÌÏ v ma fan...',
       'ÌÏ wait 4 me in sch i finish ard 5..'], dtype=object)

In [40]:
#mengubah kolom ke array
X =df["message"].values 
y = df["class"].values
# membuat objek vektor
cv = CountVectorizer()
#transform nilai 
X = cv.fit_transform(X)
v= X.toarray()

print(v)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [41]:
#menggeser kolom target ke akhir
first_col = df.pop('message')
df.insert(0, 'message', first_col)
df

message class
0     Go until jurong point, crazy.. Available only ...   ham
1                         Ok lar... Joking wif u oni...   ham
2     Free entry in 2 a wkly comp to win FA Cup fina...  spam
3     U dun say so early hor... U c already then say...   ham
4     Nah I don't think he goes to usf, he lives aro...   ham
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...  spam
5568              Will Ì_ b going to esplanade fr home?   ham
5569  Pity, * was in mood for that. So...any other s...   ham
5570  The guy did some bitching but I acted like i'd...   ham
5571                         Rofl. Its true to its name   ham

[5572 rows x 2 columns]

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)

In [43]:
bnb = BernoulliNB(binarize=0.0)
model = bnb.fit(X_train, y_train)
y_pred_train= bnb.predict(X_train)
y_pred_test = bnb.predict(X_test)

In [44]:
print(bnb.score(X_train, y_train)*100)
print(bnb.score(X_test, y_test)*100)

98.64102564102564
97.42822966507177


In [45]:
#training set 
from sklearn.metrics import classification_report
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      3391
        spam       1.00      0.90      0.95       509

    accuracy                           0.99      3900
   macro avg       0.99      0.95      0.97      3900
weighted avg       0.99      0.99      0.99      3900



In [46]:
#testing set 
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.99      1434
        spam       0.98      0.84      0.90       238

    accuracy                           0.97      1672
   macro avg       0.98      0.92      0.94      1672
weighted avg       0.97      0.97      0.97      1672

